name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        working-directory: ./
        run: npm ci

      - name: Run builds
        working-directory: ./
        run: npm run build

      - name: Run tests
        working-directory: ./
        run: npm run test
